### ISSUE TITLE
Static links to figures

### ISSUE THREAD

**Issue by dominikbruechner** [PerMedCoE/observatory_benchmark#1]
To make the import of the markdown to oeb easier, please add static links to the figures (can be hosted with oeb, or stay in the git repo).

Example:
`![Figure 1. Cell counts for the three cell populations tools after 120 minutes of simulation](https://github.com/PerMedCoE/observatory_benchmark/raw/main/figures/Fig1.png)`

Thanks!

**Comment by ArnauMontagud** [comment]
Static links to the figures defined.
